sudo: false

os: linux

dist: trusty

language: ruby

rvm:
  - '2.1'
  - '2.2'
  - '2.3'
  - '2.4'
  - '2.5'

matrix:
  fast_finish:
    true

notifications:
  email: false

addons:
  apt:
    packages:
      - gcc
      - make
      - ruby
      - ruby-dev
      - rake
      - libatlas-base-dev
      - libopenblas-dev
      - liblapack-dev
      - liblapacke-dev

before_install:
  - gem install --no-document bundler -v '~> 1.16'

install:
  - bundle install --jobs=3 --retry=3

script:
  - gem build numo-linalg.gemspec
  - gem install numo-linalg-*.gem
  - rspec --format documentation spec
